name: wembley_studios_movies
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^6.0.5
  http: ^0.13.5
  sqflite: ^2.2.4+1
  rxdart: ^0.27.7


flutter_native_splash:
  image: assets/images/icon.png
  color: "#000000"
  android: true
  android_12: 
    image: assets/images/icon.png
    fullscreen: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0

flutter:

  uses-material-design: true